name: Run linter and build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        # TODO(RSDK-10636): run the build on windows-2019, too, when it's is tolerably fast
        runs_on: [ubuntu-22.04, ubuntu-22.04-arm, macos-14, macos-13]
    name: "Lint and build on each platform"
    runs-on: ${{ matrix.runs_on }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v3
        with:
          path: ~/.conan2
          key: ${{ matrix.runs_on }}-conan-${{ hashFiles('**/conanfile.py') }}
          restore-keys: |
            ${{ matrix.runs_on }}-conan-

      - name: Install dependencies
        run: make setup

      - name: Run lint
        run: make lint

      - name: Build
        run: make tflite_cpu

  # PRs should only be mergeable when all platforms can build the code. Instead of having 1
  # requirement for each platform in the Github settings, have 1 rule that depends on every item
  # from the previous matrix, and have the Github check gate on this one.
  allow:
    name: "Lint and build"
    needs: build
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Check whether all builds completed
        run: |
          echo "Results of builds: ${{ needs.build.result }}"
          [ "${{ needs.build.result }}" == "success" ]
