name: Run linter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: "Lint and build"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run lint
        run: make lint

      - uses: actions/cache@v3
        with:
          path: ~/.conan2
          key: ${{runner.os}}-conan-${{ hashFiles('**/conanfile.py') }}
          restore-keys: |
            ${{ runner.os }}-conan-

      - name: Install dependencies
        run: make setup

      - name: Build
        run: make tflite_cpu
